spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters: []
      routes: []  # definir quando os serviços subirem
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
