server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petshop_appointment?useSSL=false&serverTimezone=UTC
    username: dev
    password: dev
  data:
    redis:
      host: localhost
      port: 6379
